version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT:
      DATABASE_NAME:
      DATABASE_HOST:
      DATABASE_PORT:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./data:/var/lib/postgresql/data